#!/bin/sh

function APPEND_PATH {
	echo $PATH | grep -oE "(^|:)$mm(:|$)" > /dev/null
	[ $? -eq 0 ] || export PATH="$PATH:$1"
}
function INSERT_PATH {
	echo $PATH | grep -oE "(^|:)$mm(:|$)" > /dev/null
	[ $? -eq 0 ] || export PATH="$1:$PATH"
}


if [ ! -z $FLATPAK_ID ];then
	export PS1="[📦 $FLATPAK_ID \W]\$ "
fi

if [ ! -z $ENV_HOME_LOADED ];then
	return
else
	export ENV_HOME_LOADED=1
fi

if [ ! -z "$WSL_DISTRO_NAME" ];then
	source /etc/profile.d/flatpak.sh
	export QT_QPA_PLATFORM=wayland
	[[ "$(genie -r)" != "stopped" ]] || genie -i
fi


export GST_VAAPI_ALL_DRIVERS=1
export QT_XCB_GL_INTEGRATION=xcb_egl
export QT_LOGGING_RULES='xdg-desktop*.debug=true;xdp-kde*.debug=true'
#XDG

# export xdg, if not defined
if [ ! $XDG_CONFIG_HOME ]; then
	export XDG_CACHE_HOME=$HOME/.cache
	export XDG_CONFIG_HOME=$HOME/.config
	export XDG_DATA_HOME=$HOME/.local/share
	export XDG_STATE_HOME=$HOME/.local/state
fi

mkdir -p $XDG_CONFIG_HOME

export ZES_ENABLE_SYSMAN=1

#cmake
export CMAKE_EXPORT_COMPILE_COMMANDS=1


#export FLATPAK_GL_DRIVERS=mesa-git

#vscode
export FLATPAK_ENABLE_SDK_EXT='*'

#wget
#export WGETRC=$XDG_CONFIG_HOME/wgetrc
#[ -e "$WGETRC" ] || touch "$WGETRC" 

#java
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java -Djavafx.verbose=true -Dprism.verbose=true"

MY_CACHE_HOME=$HOME/.cache
MY_CONFIG_HOME=$HOME/.config
MY_DATA_HOME=$HOME/.local/share
MY_STATE_HOME=$HOME/.local/state

#
APPEND_PATH /etc/ostree-bin
export SSH_KEY_PATH=~/.ssh/rsa_id
export DEFAULT_USER=`whoami`
export EDITOR=nvim
export SYSTEMD_EDITOR=nvim
# export VIMINIT="source $MY_CONFIG_HOME/vim/vimrc"
export PASSWORD_STORE_DIR=$MY_CONFIG_HOME/password-store
export WINEPREFIX=$MY_DATA_HOME/wine

export XINITRC=$MY_CONFIG_HOME/X11/xinitrc
export XSERVERRC=$MY_CONFIG_HOME/X11/xserverrc

#export XCURSOR_PATH=$MY_DATA_HOME/icons:/usr/share/icons:/run/host/share/icons:/run/host/user-share/icons

export LESSHISTFILE="$MY_STATE_HOME"/less/history

export GDBHISTFILE=$MY_DATA_HOME/gdb/history

#kde
export KDEHOME=$MY_CONFIG_HOME/kde

#java

#python
export PYTHONSTARTUP=$MY_DATA_HOME/python/setup.py

#elinks
export ELINKS_CONFDIR=$MY_CONFIG_HOME/elinks

#bash
export BASH_COMPLETION_USER_FILE=$MY_CONFIG_HOME/bash-completion/bash_completion

#npm
export NPM_CONFIG_USERCONFIG=$MY_CONFIG_HOME/npm/npmrc
APPEND_PATH $MY_DATA_HOME/npm/bin
export NODE_PATH=$MY_DATA_HOME/npm/lib/node_modules
#docker
export DOCKER_CONFIG=$MY_CONFIG_HOME/docker
export MACHINE_STORAGE_PATH=$MY_DATA_HOME/docker-machine

#DXVK
export DXVK_STATE_CACHE_PATH=/home/out/Sync/.cache/dxvk
#export DXVK_CONFIG_FILE=/home/out/.config/dxvk/dxvk.conf
export DXVK_LOG_PATH=/home/out/Sync/.cache/dxvk
#export DXVK_HUD=fps
#export DXVK_FRAME_RATE=60
#export DXVK_FILTER_DEVICE_NAME=Intel

#ANDORID
export ANDROID_HOME=$MY_DATA_HOME/Android/Sdk
export NDK=$ANDROID_HOME/ndk-bundle
APPEND_PATH $ANDROID_HOME/platform-tools
APPEND_PATH $ANDROID_HOME/tools

#Flutter
APPEND_PATH /opt/flutter/bin
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export PUB_HOSTED_URL=https://pub.flutter-io.cn

#Gtk
export GTK_RC_FILES=$MY_CONFIG_HOME/gtk-1.0/gtkrc
export GTK2_RC_FILES=$MY_CONFIG_HOME/gtk-2.0/gtkrc

#Cargo
export CARGO_HOME=$MY_DATA_HOME/cargo
export RUSTUP_HOME=$MY_DATA_HOME/rustup
APPEND_PATH $CARGO_HOME/bin

#Go
export GOPATH=$MY_DATA_HOME/go
#export GOROOT=$GOPATH/sdk
APPEND_PATH $GOPATH/bin

#conan
export CONAN_USER_HOME=$MY_CONFIG_HOME/conan
#Gradle
export GRADLE_USER_HOME=$MY_DATA_HOME/gradle
#FFmpeg
export FFMPEG_DATADIR=$MY_CONFIG_HOME/ffmpeg
#nv
export CUDA_CACHE_PATH=$MY_CONFIG_HOME/nv
#dotnet
export DOTNET_CLI_HOME=$MY_DATA_HOME/dotnet

#.z
export _Z_DATA=$MY_DATA_HOME/z


export MCHRDIR=/opt/chroot
#export PATH=$PATH:/usr/lib/dart/bin

#IM
#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

export LUA_PATH="${LUA_PATH:+${LUA_PATH}:}$MY_DATA_HOME/luarocks/share/lua/5.4/?.lua;$MY_DATA_HOME/luarocks/share/lua/5.4/?/init.lua;"

export DOTNET_ROOT=$MY_STATE_HOME/dotnet

# nix
NIX_SH=$HOME/.nix-profile/etc/profile.d/nix.sh
if [ -e "$NIX_SH" ];then
    . "$NIX_SH"
fi
NIX_HM=$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
if [ -e "$NIX_HM" ];then
    export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}
    . "$NIX_HM"
fi

export STACK_XDG=1

# bat
if [ -x "$(command -v bat)" ];then
	export MANPAGER='sh -c "col -bx | bat -pl man --theme=Monokai\ Extended"'
	export MANROFFOPT='-c'
fi

#if [[ $TERM_PROGRAM = 'vscode' ]]; then
#    export DISPLAY=:0
#    export WAYLAND_DISPLAY=wayland-0
#    export XDG_RUNTIME_DIR=/run/user/1000
#fi

INSERT_PATH $HOME/.local/bin
