---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ~/.config/docker/config/calibre-web:/config
      - ~/Documents/books:/books
    ports:
      - 6802:8083
    restart: unless-stopped
